name: Train_and_Test

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'
jobs:
  Train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: docker build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd_test_v1:assgn3_v1 .


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker push 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd_test_v1:assgn3_v1
  
  Test:
    needs: Train
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/cicd_test_v1:assgn3_v1

      - name: Run Docker container and evalute score
        run: |
          OUTPUT=$(docker run ${{ secrets.DOCKER_USERNAME }}/cicd_test_v1:assgn3_v1)
          echo "Test Score:$OUTPUT "
          if [[ `echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
